name: cs50xmiami
channels:
  - conda-forge
dependencies:
  - python=3.4.3
  - anaconda
  - flask
  - flask_assets
  - Jinja2
  - openssl
  - flask-login
  - flask-migrate
  - flask-sqlalchemy
  - flask-wtf
  - pip
  - pip:
    - gunicorn